name: check content

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install dependencies
        run: |-
          pip install aiohttp

      - name: check apps' health and refresh the cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          python scripts/curate.py check --dir apps

      - name: config bot
        run: |-
          git config --global user.email "readme-bot@fossapps.com"
          git config --global user.name "readme-bot"

      - name: commit and push if something changed
        run: |-
          git add -A
          git commit -m "bot: update cache" || exit 0
          git push